### ISSUE TITLE
Update NuGet Dependency to OpenTK 2.0

### ISSUE THREAD

**Issue by MutterOberin** [opcon/QuickFont#25]
Update Dependency for Nuget Package from OpenTK.Next to OpenTK 2.0 Release

[OpenTK](https://github.com/opentk/opentk) Released 2016-09-23

**Comment by opcon** [comment]
Thanks for the heads up, I'll do this soon

**Comment by MutterOberin** [comment]
Thanks!

**Comment by opcon** [comment]
I've just published QuickFont 4.4 which updates the OpenTK dependency to 2.0. Feel free to open a new issue if anything is wrong with it :)
