### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MutterOberin** [opcon/QuickFont#42]
I am trying to use this nice project but get a "BadImageFormatException" right away.

Directly by calling "new QFont(font, size, new QFontBuilderConfiguration(true))"

**Comment by MutterOberin** [comment]
Looks like the freetype6.dll under SharpFont.Dependencies.2.6 is wrongly copied from the x86 instead of x64 folder when building. This might be caused by the "any" configuration. Anyone running into this issue should try to replace the dll manually.

**Comment by opcon** [comment]
Hi @MutterOberin,

Thanks for diagnosing the error! I might have a look at the configuration, and see why the wrong dll is being copied.

**Comment by opcon** [comment]
For now, the best thing to do is manually tell Visual Studio to copy the proper freetype.dll file the output directory, by adding it as a resource in a project that uses QuickFont.
There is currently no support for determining which version of freetype is needed.
